workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    scripts:
      - script: xcode-project use-profiles
      - script: flutter packages pub get
      - name: Flutter build unsigned ipa and automatic versioning
        script: flutter build ios --debug --no-codesign #--export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - sssoft2023@gmail.com