workflows:
  ios-workflow:
    name: appetize simulator build
    scripts:
        - name: Build unsigned .app
          script: | 
            xcodebuild -workspace "ios/Runner.xcworkspace" \
              -scheme "$XCODE_SCHEME" \
              -configuration "Debug" \
              -sdk iphonesimulator \
              -derivedDataPath ios/output
            # If you are building a project instead of a workspace:
            # xcodebuild -project "ios/Runner.xcodeproj" \
            #   -scheme "$XCODE_SCHEME" \
            #   -configuration "Debug" \
            #   -sdk iphonesimulator \
            #   -derivedDataPath ios/output
        - name: Create a .zip archive
          script: | 
            cd ios/output/Build/Products/Debug-iphonesimulator
            zip -r ios_app.zip $XCODE_SCHEME.app
    artifacts:
      - ios/output/Build/Products/Debug-iphonesimulator/*.zip
    publishing:
      email:
        recipients:
          - sssoft2023@gmail.com